# Import Libaries

In [5]:
import numpy as np
import pandas as pd

In [6]:
crop = pd.read_csv("Crop_recommendation.csv")
crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Testinng the dataset

In [7]:
crop.shape

(2200, 8)

In [8]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [9]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [10]:
crop.duplicated().sum()

np.int64(0)

In [11]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [12]:
crop['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

# giving numbers to names

In [13]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [14]:
crop

,N,P,K,temperature,humidity,ph,rainfall,label,crop_num
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,1
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,1
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,1
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,1
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,1
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee,22
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee,22
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee,22
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee,22
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee,22

In [15]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

    N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

# Train Test Split

In [16]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [17]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
regr.fit(X,y)
print(regr.predict([[107,34,32,26.774637,66.413269,6.780064,177.774507]]))

[8.76546515]

C:\Users\revan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [18]:
X

        N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [19]:
y.shape

(2200,)

In [20]:

from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
X_train

        N    P    K  temperature   humidity        ph    rainfall
1656   17   16   14    16.396243  92.181519  6.625539  102.944161
752    37   79   19    27.543848  69.347863  7.143943   69.408782
892     7   73   25    27.521856  63.132153  7.288057   45.208411
1041  101   70   48    25.360592  75.031933  6.012697  116.553145
1179    0   17   30    35.474783  47.972305  6.279134   97.790725
...   ...  ...  ...          ...        ...       ...         ...
1638   10    5    5    21.213070  91.353492  7.817846  112.983436
1095  108   94   47    27.359116  84.546250  6.387431   90.812505
1130   11   36   31    27.920633  51.779659  6.475449  100.258567
1294   11  124  204    13.429886  80.066340  6.361141   71.400430
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[1760 rows x 7 columns]


# Scale the features using MinMaxScaler

In [23]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [24]:
X_train

array([[0.12142857, 0.07857143, 0.045     , ..., 0.9089898 , 0.48532225,
        0.29685161],
       [0.26428571, 0.52857143, 0.07      , ..., 0.64257946, 0.56594073,
        0.17630752],
       [0.05      , 0.48571429, 0.1       , ..., 0.57005802, 0.58835229,
        0.08931844],
       ...,
       [0.07857143, 0.22142857, 0.13      , ..., 0.43760347, 0.46198144,
        0.28719815],
       [0.07857143, 0.85      , 0.995     , ..., 0.76763665, 0.44420505,
        0.18346657],
       [0.22857143, 0.52142857, 0.085     , ..., 0.56099735, 0.54465022,
        0.11879596]])

# Training Models

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    # print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    # print("==========================================================")

Logistic Regression  with accuracy : 0.9181818181818182
Naive Bayes  with accuracy : 0.9954545454545455
Support Vector Machine  with accuracy : 0.9681818181818181
K-Nearest Neighbors  with accuracy : 0.9704545454545455
Decision Tree  with accuracy : 0.9863636363636363
Random Forest  with accuracy : 0.9931818181818182
Bagging  with accuracy : 0.9863636363636363
AdaBoost  with accuracy : 0.14545454545454545
Gradient Boosting  with accuracy : 0.9818181818181818
Extra Trees  with accuracy : 0.8909090909090909

In [26]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train,y_train)
ypred = gbc.predict(X_test)
accuracy_score(y_test,ypred)

0.9818181818181818

In [27]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9931818181818182

In [28]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import pickle

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

with open('standscaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

rfc = RandomForestClassifier()
rfc.fit(X_train_scaled, y_train)

ypred = rfc.predict(X_test_scaled)
accuracy = accuracy_score(y_test, ypred)

print("Accuracy:", accuracy)

Accuracy: 0.9931818181818182

In [29]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9954545454545455

# Predictive System

In [30]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0]

In [31]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[6]
Papaya is a best crop to be cultivated

In [32]:
# new inputs 2


N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[6]
Papaya is a best crop to be cultivated

In [33]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[6]
Papaya is a best crop to be cultivated

In [34]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))

In [35]:
df = pd.read_csv("yield.csv")
df.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Tamil Nadu,ARIYALUR,2008,Kharif,Rice,24574,NaN
1,Tamil Nadu,ARIYALUR,2008,Whole Year,Arhar/Tur,209,NaN
2,Tamil Nadu,ARIYALUR,2008,Whole Year,Bajra,565,NaN
3,Tamil Nadu,ARIYALUR,2008,Whole Year,Banana,190,NaN
4,Tamil Nadu,ARIYALUR,2008,Whole Year,Cashewnut,31113,NaN

In [36]:
df.dropna(inplace=True)

In [37]:
# Encode categorical variables
from sklearn.preprocessing import StandardScaler, LabelEncoder
label_enc_district = LabelEncoder()
label_enc_crop = LabelEncoder()
df['District_Code'] = label_enc_district.fit_transform(df['District_Name'])
df['Crop_Code'] = label_enc_crop.fit_transform(df['Crop'])

# Select relevant columns
df = df[['District_Name', 'Crop', 'Area', 'Production']]  # Assuming these columns exist

In [38]:
df['Yield'] = df['Production'] / df['Area']

In [39]:
df['District_Name'] = df['District_Name'].astype(str).str.strip()
df['Crop'] = df['Crop'].astype(str).str.strip()
df['District_Code'] = label_enc_district.fit_transform(df['District_Name'])
df['Crop_Code'] = label_enc_crop.fit_transform(df['Crop'])

print(df.columns)  # Check available columns
print(df.head())   # Check if 'District_Code' and 'Crop_Code' are present

Index(['District_Name', 'Crop', 'Area', 'Production', 'Yield', 'District_Code',
       'Crop_Code'],
      dtype='object')
   District_Name           Crop   Area  Production      Yield  District_Code  \
22      ARIYALUR           Rice  25978     80462.0   3.097313              0
23      ARIYALUR  Small millets    404       649.0   1.606436              0
24      ARIYALUR      Arhar/Tur    160       122.0   0.762500              0
25      ARIYALUR          Bajra    644      1082.0   1.680124              0
26      ARIYALUR         Banana    134      5761.0  42.992537              0

    Crop_Code
22         64
23         68
24          2
25          4
26          5

In [40]:

# Split dataset into features and target
X = df[['District_Code', 'Crop_Code']]
y = df['Yield']

In [41]:

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
print(df[['District_Name', 'District_Code', 'Crop', 'Crop_Code']].head())

   District_Name  District_Code           Crop  Crop_Code
22      ARIYALUR              0           Rice         64
23      ARIYALUR              0  Small millets         68
24      ARIYALUR              0      Arhar/Tur          2
25      ARIYALUR              0          Bajra          4
26      ARIYALUR              0         Banana          5

In [43]:

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_error, mean_squared_error
models = {
    "Random Forest": RandomForestRegressor(),
    "Gradient Boosting": GradientBoostingRegressor(),
    "Linear Regression": LinearRegression()
}

best_model = None
best_mae = float("inf")

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    mae = mean_absolute_error(y_test, y_pred)
    print(f"{name} - Mean Absolute Error: {mae}")
    if mae < best_mae:
        best_mae = mae
        best_model = model

print(f"Best Model: {best_model}")

Random Forest - Mean Absolute Error: 113.25413581624903
Gradient Boosting - Mean Absolute Error: 116.69911773670519
Linear Regression - Mean Absolute Error: 133.47051380377036
Best Model: RandomForestRegressor()

In [45]:


# Train Random Forest model
model = RandomForestRegressor()
model.fit(X_train_scaled, y_train)

RandomForestRegressor()

In [46]:

# Evaluate model
y_pred = model.predict(X_test_scaled)

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

Mean Absolute Error: 114.18681665705725
Mean Squared Error: 1066955.6478357462

In [47]:

# Function for prediction
def predict_yield(district_name, crop_name, area):
    # Check if the district and crop exist in the trained encoders
    if district_name not in label_enc_district.classes_:
        raise ValueError(f"District '{district_name}' not found in training data.")
    if crop_name not in label_enc_crop.classes_:
        raise ValueError(f"Crop '{crop_name}' not found in training data.")
    
    # Convert district and crop names to numerical labels
    district_num = label_enc_district.transform([district_name])[0]
    crop_num = label_enc_crop.transform([crop_name])[0]
    
    # Prepare input and scale it
    input_features = np.array([[district_num, crop_num]])
    input_features_scaled = scaler.transform(input_features)
    
    # Predict yield
    predicted_yield = model.predict(input_features_scaled)
    return (predicted_yield[0])*area

In [48]:
# Save the model and scaler
import pickle
pickle.dump(model, open("yieldmodel.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

In [49]:
print(predict_yield("ARIYALUR", "Rice",1))

3.6319810247553495

C:\Users\revan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [50]:
df['District_Name'].unique()

array(['ARIYALUR', 'COIMBATORE', 'CUDDALORE', 'DHARMAPURI', 'DINDIGUL',
       'ERODE', 'KANCHIPURAM', 'KANNIYAKUMARI', 'KARUR', 'KRISHNAGIRI',
       'MADURAI', 'NAGAPATTINAM', 'NAMAKKAL', 'PERAMBALUR', 'PUDUKKOTTAI',
       'RAMANATHAPURAM', 'SALEM', 'SIVAGANGA', 'THANJAVUR',
       'THE NILGIRIS', 'THENI', 'THIRUVALLUR', 'THIRUVARUR',
       'TIRUCHIRAPPALLI', 'TIRUNELVELI', 'TIRUPPUR', 'TIRUVANNAMALAI',
       'TUTICORIN', 'VELLORE', 'VILLUPURAM', 'VIRUDHUNAGAR'], dtype=object)

In [51]:
df['Crop'].unique()

array(['Rice', 'Small millets', 'Arhar/Tur', 'Bajra', 'Banana',
       'Cashewnut', 'Castor seed', 'Coconut', 'Coriander', 'Cotton(lint)',
       'Dry chillies', 'Groundnut', 'Jowar', 'Maize', 'Moong(Green Gram)',
       'Onion', 'Ragi', 'Sesamum', 'Sugarcane', 'Sunflower',
       'Sweet potato', 'Tapioca', 'Turmeric', 'Urad', 'Horse-gram',
       'Tobacco', 'Black pepper', 'Cardamom', 'Gram', 'Pulses total',
       'Total foodgrain', 'Wheat', 'Sannhamp', 'Korra', 'Samai',
       'Guar seed', 'Other Cereals & Millets', 'Other Kharif pulses',
       'Rapeseed &Mustard', 'Varagu', 'Ash Gourd',
       'Beans & Mutter(Vegetable)', 'Beet Root', 'Bhindi', 'Bitter Gourd',
       'Bottle Gourd', 'Brinjal', 'Cauliflower', 'Citrus Fruit',
       'Cucumber', 'Drum Stick', 'Garlic', 'Grapes', 'Jack Fruit',
       'Lab-Lab', 'Mango', 'Orange', 'Other Citrus Fruit',
       'Other Fresh Fruits', 'Other Vegetables', 'Papaya', 'Pome Fruit',
       'Pome Granet', 'Redish', 'Ribed Guard', 'Snak Guard', 'Tomato',
       'Water Melon', 'Yam', 'Cabbage', 'Pump Kin', 'Dry ginger',
       'Arecanut', 'Potato', 'Carrot', 'Pineapple', 'Mesta', 'Apple',
       'Peach', 'Pear', 'Plums', 'Turnip', 'Litchi', 'Ber'], dtype=object)

In [52]:
crop_dicty = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22,

    # Assigning numbers starting from 23 to the remaining crops
    'small millets': 23,
    'arhar/tur': 24,
    'bajra': 25,
    'cashewnut': 26,
    'castor seed': 27,
    'coriander': 28,
    'cotton(lint)': 29,
    'dry chillies': 30,
    'groundnut': 31,
    'jowar': 32,
    'moong(green gram)': 33,
    'onion': 34,
    'ragi': 35,
    'sesamum': 36,
    'sugarcane': 37,
    'sunflower': 38,
    'sweet potato': 39,
    'tapioca': 40,
    'turmeric': 41,
    'urad': 42,
    'horse-gram': 43,
    'tobacco': 44,
    'black pepper': 45,
    'cardamom': 46,
    'gram': 47,
    'pulses total': 48,
    'total foodgrain': 49,
    'wheat': 50,
    'sannhamp': 51,
    'korra': 52,
    'samai': 53,
    'guar seed': 54,
    'other cereals & millets': 55,
    'other kharif pulses': 56,
    'rapeseed &mustard': 57,
    'varagu': 58,
    'ash gourd': 59,
    'beans & mutter(vegetable)': 60,
    'beet root': 61,
    'bhindi': 62,
    'bitter gourd': 63,
    'bottle gourd': 64,
    'brinjal': 65,
    'cauliflower': 66,
    'citrus fruit': 67,
    'cucumber': 68,
    'drum stick': 69,
    'garlic': 70,
    'jack fruit': 71,
    'lab-lab': 72,
    'other citrus fruit': 73,
    'other fresh fruits': 74,
    'other vegetables': 75,
    'pome fruit': 76,
    'pome granet': 77,
    'redish': 78,
    'ribed guard': 79,
    'snak guard': 80,
    'tomato': 81,
    'yam': 82,
    'cabbage': 83,
    'pump kin': 84,
    'dry ginger': 85,
    'arecanut': 86,
    'potato': 87,
    'carrot': 88,
    'pineapple': 89,
    'mesta': 90,
    'peach': 91,
    'pear': 92,
    'plums': 93,
    'turnip': 94,
    'litchi': 95,
    'ber': 96
}